const Pikachu = {
Pokedex_entries:  ["Yellow:  It keeps its tail raised to monitor its surroundings. If you yank its tail, it will try to bite you.", "Gold: This intelligent POKéMON roasts hard BERRIES with electricity to make them tender enough to eat.", "Red/Blue: When several of these POKéMON gather, their electricity could build and cause lightning storms.", "Gold: It raises its tail to check its surroundings. The tail is sometimes struck by lightning in this pose.", "Crystal:	When it is angered, it immediately discharges the energy stored in the pouches in its cheeks.", "Ruby:	Whenever PIKACHU comes across something new, it blasts it with a jolt of electricity. If you come across a blackened berry, it’s evidence that this POKéMON mistook the intensity of its charge.", "Sapphire:	This POKéMON has electricity-storing pouches on its cheeks. These appear to become electrically charged during the night while PIKACHU sleeps. It occasionally discharges electricity when it is dozy after waking up.", "FireRed:	It has small electric sacs on both its cheeks. If threatened, it looses electric charges from the sacs.", "Emerald:	It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.", "Diamond:	It lives in forests with others. It stores electricity in the pouches on its cheeks.", "Pearl:	If it looses crackling power from the electric pouches on its cheeks, it is being wary.", "Platinum:	It occasionally uses an electric shock to recharge a fellow PIKACHU that is in a weakened state.", "HeartGold:	This intelligent Pokémon roasts hard berries with electricity to make them tender enough to eat.", "SoulSilver:	It raises its tail to check its surroundings. The tail is sometimes struck by lightning in this pose.", "Black/White/Black 2/White 2:	It occasionally uses an electric shock to recharge a fellow Pikachu that is in a weakened state.", "Omega Ruby:	Whenever Pikachu comes across something new, it blasts it with a jolt of electricity. If you come across a blackened berry, it’s evidence that this Pokémon mistook the intensity of its charge.", "Sun:	A plan was recently announced to gather many Pikachu and make an electric power plant.", "Moon:	It’s in its nature to store electricity. It feels stressed now and then if it’s unable to fully discharge the electricity.", "Ultra Sun:	Its nature is to store up electricity. Forests where nests of Pikachu live are dangerous, since the trees are so often struck by lightning.", "Ultra Moon:	While sleeping, it generates electricity in the sacs in its cheeks. If it’s not getting enough sleep, it will be able to use only weak electricity.", "Shield:	When Pikachu meet, they’ll touch their tails together and exchange electricity through them as a form of greeting", "Sword:	Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.", ""],
Appearance: ["https://www.serebii.net/swordshield/pokemon/025.png", "https://www.serebii.net/Shiny/SWSH/025.png"],
Stats: "https://i.stack.imgur.com/dNh2P.png",
Notable_Anime_appearances: "Too many to count because he's been in almost every anime episode",
Smogon_Tier: "   Written by:steviestar   Tier: NU                     Overview: With its signature item, Light Ball, Pikachu might seem like an incredibly dominating threat with offensive stats rivaling some Ubers; however, there are far too many things holding Pikachu back from being effective. Pikachu's main downfall should be fairly obvious: its bulk is absolutely pathetic--even lower than the likes of Haunter or Kadabra. While Pikachu can mitigate its frailty somewhat with Substitute, Encore, and its ability, Lightning Rod, its second downfall isn't as easy to overlook. The very Light Ball that makes Pikachu viable is also what makes it so limited; as Pikachu needs its Light Ball to not be complete dead weight, it is unable to use any other item, including Life Orb and all Choice items. Thus, Pikachu will not hit as hard as you might think it would: traditional powerhouses greatly depend on the boosts these items provide, while Pikachu has to do without. Successfully using Pikachu will require massive amounts of team support and top-level prediction.",
Lore_and_Background: "This is the most iconic ever, Pikachu is the electric mouse pokemon, although the original creator of pokemon actually admits that he based the design of pikachu off of a squirrel, not a mouse. Of course his appearances in the pokemon anime also are central to his lore. ash's pikachu started out as a pchu, who by chance stumbled across a group of kangaskhans, pichu befriended one of the kangaskhans, and then was pretty much a secondory child of the kangaskhan. Eventually though, pikachu decided to leave the pack, but after thinking about them evolved into a pikachu, and eventually came across and came with proffesor oak back to his lab. Then pikachu came across Ash. After showing his care for pokemon, Ash receives pikachu's respect, and the rest is history"
}

const Infernape = {
Pokedex_entries: ["Diamond:	It uses a special kind of martial arts involving all its limbs. Its fire never goes out.", "Pearl:	Its crown of fire is indicative of its fiery nature. It is beaten by none in terms of quickness.", "Platinum:	It uses unique fighting moves with fire on its hands and feet. It will take on any opponent.", "HeartGold/SoulSilver:	It tosses its enemies around with agility. It uses all its limbs to fight in its own unique style."],
Appearance: ["https://img.pokemondb.net/sprites/x-y/normal/infernape.png", "https://img.pokemondb.net/sprites/x-y/shiny/infernape.png"],
Stats: "https://pm1.narvii.com/5806/525432ef57596a7e91e8cf87d20066d24db708dc_hq.jpg",
Notable_Anime_appearances: "",
Smogon_Tier: "Written by: Hilomilo   Tier: UU                         Overview: Infernape is among the UnderUsed metagame's premier offensive threats, thanks to its multitude of valuable traits. Between a great Speed tier, good mixed offenses, and access to both physical and special boosting moves in Swords Dance and Nasty Plot, Infernape is extremely offensively versatile, capable of running several different viable sets and always leaving its opponent guessing. Furthermore, Infernape's excellent STAB combination in tandem with the massive amount of coverage options at its disposal allows it to hit almost the entire tier for super effective damage, severely limiting its checks. Access to two powerful STAB priority attacks in the forms of Mach Punch and Vacuum Wave further bolsters Infernape's offensive prowess, allowing it to pick off weakened threats with relative ease. Unfortunately, Infernape can often suffer from four-moveslot syndrome, which prevents it from covering everything it'd like to and allows certain Pokemon to check some of its sets. Infernape is also very frail without defensive investment, which leaves it extremely vulnerable to Pokemon that can hit it for super effective damage, such as Moltres and Mega Aerodactyl. Infernape also sits at a slightly exploitable Speed tier, given that big threats like Gengar and Latias can outpace and threaten it, which in tandem with its poor bulk can require intelligent play to put Infernape to full use.",
Lore_and_Background: 'Infernape, the objectively best pokemon is based on Sun WuKong, the magical king monkey born from a rock who was the main character of the book "Journey to the West", one of the 4 great classic novels of china, or in chinese called: 四大名著. Infernape to pay homage to his origin, has a crown of fire and gold, and gold-like armour pieces on its knees, elbows, and chest, although infernape doesnt carry the signature   '
}

const Lucario = {
Pokedex_entries: ["Diamond:	It has the ability to sense the auras of all things. It understands human speech.", "Pearl:	By catching the aura emanating from others, it can read their thoughts and movements.", "Platinum:	A well-trained one can sense auras to identify and take in the feelings of creatures over half a mile away.", "HeartGold/SoulSilver:	It’s said that no foe can remain invisible to LUCARIO, since it can detect auras. Even foes it could not otherwise see.", "Black 2/White 2:	By reading the auras of all things, it can tell how others are feeling from over half a mile away.", "Sun:	Not only does it perceive auras, but it has also gained the power to control them. It employs them in battle.", "Moon:	They can detect the species of a living being— and its emotions—from over half a mile away. They control auras and hunt their prey in packs.", "Ultra Sun:	It concentrates its mental energy and fires off mysterious waves called auras, which can crush boulders of large size to dust.", "Ultra Moon:	Lucario reads its opponent’s feelings with its aura waves. It finds out things it would rather not know, so it gets stressed out easily.", "Sword:	It controls waves known as auras, which are powerful enough to pulverize huge rocks. It uses these waves to take down its prey.", "Shield:	It can tell what people are thinking. Only Trainers who have justice in their hearts can earn this Pokémon’s trust."],
Appearance: ["https://www.serebii.net/swordshield/pokemon/448.png", "https://www.serebii.net/Shiny/SWSH/448.png"],
Stats: "https://i.imgur.com/1cyXnbZ.png",
Anime_appearances: "",
Smogon_Tier: "Credit: https://www.smogon.com/dex/dp/pokemon/lucario/                                                                          Written by: Whistle, Fuzznip, tobi10, Cyronna                    Tier: OU                                                     Overview: Lucario is one of the top offensive threats of DPP OU, boasting high Attack and Special Attack stats, decent Speed, great STAB attacks in Close Combat and Aura Sphere, and many other useful attacking options. Its immunity to Toxic Spikes and numerous 4x and 2x resistances (most notably to Rock-, Dark-, and Dragon-type attacks) give Lucario many opportunities to switch in and wreak havoc on the opposing team. While it does have auspicious typing, Lucario's defensive stats leave much to be desired, and its relative frailty remains its largest weakness. In spite of that, Lucario is an extremely worthwhile addition to any team, and is almost certain to leave its mark on the opponent.",
Lore_and_Background: "Lucario's apperance is possibly based on the egyptian god of death Anubis, Or also possibly based on Hermanubis who was a hybrid of two gods who had the duty of conducting souls, and with the investigation of truth, it's mask is possibly on the tanuki dog or raccoon"
}

const Greninja = {
Pokedex_entries: ["X/Omega Ruby:	It creates throwing stars out of compressed water. When it spins them and throws them at high speed, these stars can split metal in two.", "Y/Alpha Sapphire:	It appears and vanishes with a ninja’s grace. It toys with its enemies using swift movements, while slicing them with throwing stars of sharpest water."],
Appearance: ["https://www.serebii.net/sunmoon/pokemon/658.png", "https://www.serebii.net/Shiny/SM/658.png"],
Stats: "https://qph.fs.quoracdn.net/main-qimg-2284e7425b79915a82fe9f71b27f9a9b",
Notable_Anime_appearances: "In episode __ of season __, he lost to Alain's mega charizard X but almost won. In episode __ season __ he won to Sawyer's Mega sceptile",
Smogon_Tier: "Credit: https://www.smogon.com/dex/sm/pokemon/greninja/  Tier: Overused  Written by:  Jordy, dk, Indigo Plateau, Nuked, Leo, Felixx, and Martin   Greninja, courtesy of its stellar Speed tier and amazing ability in Protean, is one of the OverUsed metagame's premier offensive threats, as it is more than capable of pressuring both faster, offensively inclined teams and bulkier builds. Its expansive movepool is a major contributing factor to its potency as an offensive force as well: because it has such a high number of move options, it can circumvent would-be counters and defensive checks and leave one's opponent guessing at Team Preview. Additionally, Greninja is one of the few viable offensively inclined user of Spikes and Toxic Spikes, which it is a stellar user of. Greninja only truly falls short when it comes to bulk, which renders it incapable of taking even resisted hits repeatedly, and the inability to run every coverage move on one set.",
Lore_and_Background: "Greninja is likely based off of the horned frog, it also may be inspired by the mythical ninja Jiraiya, a ninja that could turn into a giant toad"
}

module.exports = {
Greninja, 
Lucario,
Pikachu,
Infernape
}